W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  # Singular resource
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new]

  resources :notes, only: [:create, :destroy]
end

W4D5/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          default("false"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
	validates :band, :title, :year, presence: true
	validates :live, inclusion: { in: [true, false] }

	belongs_to :band

	has_many :tracks,
	dependent: :destroy
end

W4D5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :ensure_signed_in

	def index
		@albums = Album.all
		render :index
	end

	def show
		@album = Album.find_by(id: params[:id])
		if @album
			render :show
		else
			flash[:errors] = "Album not found!"
			redirect_to albums_url
		end
	end

	# Nested new route
	def new
		@album = Album.new
		# @album.band_id = params[:band_id]
		render :new
	end

	def edit
		@album = Album.find_by(id: params[:id])
		if @album
			render :edit
		else
			flash[:errors] = "Album not found!"
			redirect_to albums_url
		end
	end

	def create
		@album = Album.new(album_params)
		if @album.save
			render :show
		else
			flash.now[:errors] = @album.errors.full_messages
			render :new
		end
	end

	def update
		@album = Album.find_by(id: params[:id])
		if @album
			if @album.update_attributes(album_params)
				render :show
			else
				flash.now[:errors] = @album.errors.full_messages
				render :edit
			end
		else
			flash[:errors] = "Album not found!"
			redirect_to albums_url
		end
	end

	def destroy
		@album = Album.find_by(id: params[:id])
		if @album
			@album.destroy
			render :show
		else
			flash[:errors] = "Album not found!"
			redirect_to albums_url
		end
	end

	private

	def album_params
		params.require(:album).permit(:title, :year, :live, :band_id)
	end
end

W4D5/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W4D5/music_app/app/views/albums/_album.html.erb
  <tr>
    <td><%= link_to "#{album.title}", album_url(album) %></td>
    <td><%= link_to "#{album.band.name}", band_url(album.band_id) %></td>
    <td><%= album.year %></td>
		<td><%= album.live %></td>
  </tr>

W4D5/music_app/app/views/albums/_album_form.html.erb
<% action = (submit == 'create' ? albums_url : album_url(album)) %>

<form action="<%=action%>" method="post">
	<% unless submit == 'create' %>
		<input type="hidden" name="_method" value="patch">
	<% end %>
	<%= auth_token %>

	<label for="title">Title</label>
	<input type="text" name="album[title]" id="title" value="<%=album.title%>">

	<label for="band">Band</label>
	<select name="album[band_id]" id="band">
		<option disabled <%= album.band_id ? '' : 'selected' %>
		 >--PLEASE SELECT--</option>
		<% Band.all.each do |band| %>
			<option value="<%=band.id%>" <%= album.band_id == band.id ? 'selected' : '' %>>
			<%= band.name %></option>
		<% end %>
	</select>

	<label for="year">Year</label>
	<input type="text" name="album[year]" id="year" value="<%=album.year%>">

	<label for="live">Live?</label>
	<input type="radio" name="album[live]"
		id="live" value="true" <%= album.live == true ? 'checked' : '' %>> T
	<input type="radio" name="album[live]"
		id="live" value="false" <%= album.live == false ? 'checked' : '' %>> F

	<button type="submit"><%= submit %></button>
</form>

W4D5/music_app/app/views/albums/edit.html.erb
<%= render 'album_form', album: @album, submit: 'update' %>

W4D5/music_app/app/views/albums/index.html.erb
<table>
	<tr>
		<th>Title</th>
		<th>Band Name</th>
		<th>Year</th>
		<th>Live?</th>
	</tr>
	<% @albums.includes(:band).each do |album| %>
		<%= render 'album', album: album %>
	<% end %>
</table>

W4D5/music_app/app/views/albums/new.html.erb
<%= render 'album_form', album: @album, submit: 'create' %>

W4D5/music_app/app/views/albums/show.html.erb
<%= render 'album', album: @album %>

<br>

<% @album.tracks.each do |track| %>
	<%= link_to "#{track.title}", track_url(track) %>
<% end %>

<form action="<%=edit_album_url(@album)%>" method="get">
	<%= auth_token %>
	<button type="submit">Edit</button>
</form>

<form action="<%=album_url(@album)%>" method="post">
	<input type="hidden" name="_method" value="delete">
	<%= auth_token %>
	<button type="submit">Delete</button>
</form>

<%= link_to 'Create a new track', new_album_track_url(@album) %>