W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  # Singular resource
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new]

  resources :notes, only: [:create, :destroy]
end

W4D5/music_app/app/views/layouts/_user_form.html.erb
<div class='credentials'>
	<% action = (submit == 'register' ? users_url : session_url )  %>
	<form action="<%=action%>" method="post">
		<%= auth_token %>
		<div class='email'>
			<label for="email">Email</label>
			<input type="text" name="user[email]" id="email" value="<%=user.email%>">
		</div>

		<div class='password'>
			<label for="password">Password</label>
			<input type="password" name="user[password]" id="password">
		</div>
		<button id='cred-button' type="submit"><%= submit %></button>
	</form>
</div>

W4D5/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class='app-name'>Music App</h1>
    </header>
    <div class="errors">
      <% if flash[:errors] %>
        <%= flash[:errors] %>
      <% end %>
    </div>
    <%= yield %>
    <div class='log-info'>
      <% if logged_in? %>
        <form action="<%=session_url%>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <button type="submit">Logout!</button>
        </form>
      <% else %>
        <form action="<%=new_user_url%>" method="get">
          <%= auth_token %>
          <button type="submit">Register!</button>
        </form>

        <form action="<%=new_session_url%>" method="get">
          <%= auth_token %>
          <button type="submit">Login!</button>
        </form>
      <% end %>
    </div>
  </body>
</html>