W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  # Singular resource
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new]

  resources :notes, only: [:create, :destroy]
end

W4D5/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
	validates :name, presence: true

	has_many :albums,
	dependent: :destroy
end

W4D5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
	before_action :ensure_signed_in

	def index
		@bands = Band.all
		render :index
	end

	def show
		@band = Band.find_by(id: params[:id])
		if @band
			render :show
		else
			flash[:errors] = "Band not found!"
			redirect_to bands_url
		end
	end

	def new
		@band = Band.new
		render :new
	end

	def edit
		@band = Band.find_by(id: params[:id])
		if @band
			render :edit
		else
			flash[:errors] = "Band not found!"
			redirect_to bands_url
		end
	end

	def create
		@band = Band.new(band_params)
		if @band.save
			redirect_to band_url(@band)
		else
			flash.now[:errors] = @band.errors.full_messages
			render :new
		end
	end

	def update
		@band = Band.find_by(id: params[:id])
		if @band
			if @band.update_attributes(band_params)
				render :show
			else
				flash.now[:errors] = @band.errors.full_messages
				render :edit
			end
		else
			flash.now[:errors] = "Band not found!"
			render :edit
		end
	end

	def destroy
		@band = Band.find_by(id: params[:id])
		if @band
			@band.destroy
			render :show
		else
			flash[:errors] = "Band not found!"
			redirect_to bands_url
		end
	end

	private

	def band_params
		params.require(:band).permit(:name)
	end
end

W4D5/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/music_app/app/views/bands/_band_form.html.erb
<% action = (submit == 'create' ? bands_url : band_url(band)) %>

<form action="<%=action%>" method="post">
	<% if submit != 'create' %>
		<input type="hidden" name="_method" value="patch">
	<% end %>
	<%= auth_token %>

	<label for="name">Name</label>
	<input type="text" name="band[name]" id="name" value="<%=band.name%>">

	<button type="submit"><%=submit%></button>
</form>

W4D5/music_app/app/views/bands/edit.html.erb
<%= render 'band_form', band: @band, submit: 'update' %>

W4D5/music_app/app/views/bands/index.html.erb
<% @bands.each do |band| %>
	Bands: <%= link_to "#{band.name}", band_url(band) %> <br>
<% end %>

<%= link_to 'Create a band!', new_band_url %>

W4D5/music_app/app/views/bands/new.html.erb
<%= render 'band_form', band: @band, submit: 'create' %>

W4D5/music_app/app/views/bands/show.html.erb
<%= @band.name %>

<ul>
	<% @band.albums.each do |album| %>
		<li><%= link_to "#{album.title}", album_url(album) %></li>
	<% end %>
</ul>

<%= link_to 'Create a new album', new_band_album_url(@band.id) %>